# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iOS_201' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_201
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'
  target 'iOS_201Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_201UITests' do
    # Pods for testing
  end

end
